# Generated by Django 5.1.3 on 2024-11-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio_app",
            "0002_profile_researchpaper_remove_project_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                ],
                max_length=50,
            ),
        ),
    ]
