# Generated by Django 5.1.3 on 2024-11-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0003_alter_project_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="ResearchPaper",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="profile_pics.jpg", upload_to="project_images/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(default="Evan's Portfolio", max_length=200),
        ),
    ]
